## Polynomial Regression

First import some libraries to do some data manipulation, math, and modeling.

For polynomial regression, you want to pick the order/degree based on both low training error and low test error. This means it generalizes well represent the test and training sets.

In [1]:
import numpy as np
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model, preprocessing
import numpy.polynomial.polynomial as poly
%matplotlib inline

## Import Data

Use pandas module to read the file and import into a dataframe. Print the data frame to make sure that the data is being imported correctly. Using "dataframe.values" returns a Numpy representation of the DataFrame to be spliced according to however is necessary. Reshape the feature matrix and target vector to both be of the same rank.

In [19]:
df = pd.read_csv('/Users/Farhad_Ahmed/Desktop/ML intros/ML Project/HS_Regents_Sat_Scores_2015.csv')
#print(df)
#data = df.values

# extract all the columns that we need
df1=np.stack((df['Algebra2/Trigonometry'], df['English'], df['Geometry'],df['Global History and Geography'], df['Integrated Algebra'], df['Living Environment'], df['Physical Settings/Chemistry'], df['Physical Settings/Physics'], df['Average SAT Score (Total)'])).T

#remove any empty rows
df2=(df1[~np.isnan(df1).any(axis=1)])
print(df2)
print(df2.shape)

[[  52.6   71.9   66.4   61.    64.3   64.4   63.    64.7 1265. ]
 [  64.2   72.5   65.    66.9   63.5   70.8   65.7   71.5 1367. ]
 [  77.    74.    80.9   81.8   71.6   84.8   67.9   80.2 1700. ]
 [  81.2   88.2   84.2   90.9   88.2   90.7   83.1   79.9 1889. ]
 [  81.4   75.7   79.6   88.9   80.5   87.5   76.9   72.4 1704. ]
 [  64.    78.    72.1   72.6   72.6   73.2   73.1   74.1 1327. ]
 [  84.3   93.1   74.8   79.6   72.9   76.9   71.2   79.4 1511. ]
 [  92.9   91.5   93.1   94.3   93.7   93.6   88.7   91.5 2144. ]
 [  48.5   78.5   68.7   68.9   69.4   74.4   59.1   52.3 1358. ]
 [  51.3   74.6   64.3   60.2   68.3   64.3   54.2   50.4 1147. ]
 [  45.9   72.8   59.4   74.8   69.2   75.1   61.2   36.5 1292. ]
 [  67.8   83.2   75.5   81.    73.3   81.    66.2   63.2 1479. ]
 [  64.3   72.3   68.    65.    71.3   73.2   57.5   54.7 1116. ]
 [  81.9   78.2   82.5   85.1   84.7   83.    84.3   77.8 1529. ]
 [  56.    80.5   68.6   69.9   65.3   80.1   79.5   74.6 1257. ]
 [  54.9  

Now splice the dataframe into the feature matrix and target vector.

In [23]:
# df3 will be our feature matrix
df3 = df2[:,:8]
print(df3)

# df4 will be the target vector
df4 = df2[:,8:]
print(df4)

x = np.array(df3)
y=np.array(df4)

# Check the shape of x and y vectors.
print(x.shape)
print(y.shape)



[[52.6 71.9 66.4 61.  64.3 64.4 63.  64.7]
 [64.2 72.5 65.  66.9 63.5 70.8 65.7 71.5]
 [77.  74.  80.9 81.8 71.6 84.8 67.9 80.2]
 [81.2 88.2 84.2 90.9 88.2 90.7 83.1 79.9]
 [81.4 75.7 79.6 88.9 80.5 87.5 76.9 72.4]
 [64.  78.  72.1 72.6 72.6 73.2 73.1 74.1]
 [84.3 93.1 74.8 79.6 72.9 76.9 71.2 79.4]
 [92.9 91.5 93.1 94.3 93.7 93.6 88.7 91.5]
 [48.5 78.5 68.7 68.9 69.4 74.4 59.1 52.3]
 [51.3 74.6 64.3 60.2 68.3 64.3 54.2 50.4]
 [45.9 72.8 59.4 74.8 69.2 75.1 61.2 36.5]
 [67.8 83.2 75.5 81.  73.3 81.  66.2 63.2]
 [64.3 72.3 68.  65.  71.3 73.2 57.5 54.7]
 [81.9 78.2 82.5 85.1 84.7 83.  84.3 77.8]
 [56.  80.5 68.6 69.9 65.3 80.1 79.5 74.6]
 [54.9 74.3 70.5 68.1 64.7 75.8 63.1 71.7]
 [81.7 61.6 61.8 62.8 64.1 70.3 69.8 66.7]
 [61.5 79.  74.6 76.7 71.4 74.8 74.1 80.7]
 [73.4 84.6 80.9 87.4 76.9 89.5 72.1 70.2]
 [42.4 67.7 55.6 63.2 58.8 64.2 53.4 48.8]
 [81.4 85.6 78.5 87.7 78.7 86.6 75.3 66. ]
 [76.9 83.1 77.5 80.  78.9 82.8 73.5 74.5]
 [58.2 76.5 69.2 77.6 76.4 80.5 68.9 68.7]
 [55.  67.2

## Training Set and Test Set

Here the feature matrix and target vector are both partitioned into two sets, one for training and for test.

In [ ]:
# probably not necessary if we do k-fold validation
X_tr = X[0:100,0]
Y_tr = Y[0:100,0]
X_test = X[100:200,0]
Y_test = Y[100:200,0]


kf = KFold(n_splits=10)
X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]

## Plotting the Data

To show the original shape of the training set.

In [ ]:
plt.scatter(X_tr,Y_tr)
plt.xlabel('Training set of X')
plt.ylabel('Training set of Y')
plt.show()

## Model Selection

Obtain polynomial regression models of different orders starting from linear regression i.e. degree = 1 to higher degree models like degree = 2 to 10. Find training and test error for every order and plot these errors v/s degree. Select the order that fits the data best based on low training and test error. You can use poly.polyval method from numpy to find coefficients of the different models.

In [ ]:
Errors_test = []
Errors_tr = []
for degree in range(1, 11):
    print("Degree: ", degree)
    # polyfit will return array of polynomial coefficients 
    polyCoefficients = poly.polyfit(X_tr, Y_tr, degree)
    print("Polynomial Coefficients: ", polyCoefficients)
    
    yHat_tr = poly.polyval(X_tr, polyCoefficients)
    TrainingError = np.sum(np.square(Y_tr - yHat_tr)) * 1/(2*Y_tr.shape[0])
    Errors_tr.append(TrainingError)
    print("Training Errors: ", Errors_tr)
    
    yHat_test  = poly.polyval(X_test, polyCoefficients)
    TestError = np.sum(np.square(Y_test - yHat_test)) * 1/(2*Y_test.shape[0])
    Errors_test.append(TestError)
    print("Test Errors: ", Errors_test)
    
    # creates evenly spaced numbers over a specified interval
    xAxisSpacing = np.linspace(-1, 1, 150)
    # evaluates the polynomial at all points across the xAxisSpacing
    yAxisHat = poly.polyval(xAxisSpacing, polyCoefficients)
    plt.xlim(-2,2)
    plt.ylim(-25,25)
    plt.plot(xAxisSpacing,yAxisHat, 'r-')
    plt.scatter(X_tr,Y_tr)
    plt.xlabel("Training Set of X")
    plt.ylabel("Training Set of Y")
    plt.xlim([-2,2])
    plt.show()
    
    
    

Find training and test error for every order and plot these errors v/s degree. Select the order that fits the data best based on low training and test error.

In [ ]:

degree = np.array(range(1,11))
# Plot the degree against the Training Error
plt.plot(degree,Errors_tr)
plt.xlabel("Degree Order")
plt.ylabel("Training Error")
plt.title("Training Error vs. Degree Order")
plt.grid()

In [ ]:
degree = np.array(range(1,11))
# Plot the degree against the Training Error
plt.plot(degree,Errors_test)
plt.xlabel("Degree Order")
plt.ylabel("Test Error")
plt.title("test Error vs. Degree Order")
plt.grid()